### ISSUE TITLE
Investigate label placement/collision issues

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/cartogrify#4]
This may be a core Tangram issue, but currently generated styles seem to have huge areas where labels are initially rendered but then disappear, presumably due to Tangram's label placement or collision constraints. Additionally, the precedence/priority does not seem to be quite right. This is probably an implementation error on my part.

Here is the source GL JSON style that exhibits the issue: https://tiles.stadiamaps.com/styles/alidade_smooth_dark.json (you can run a server on `localhost` to test; see https://docs.stadiamaps.com/ for auth info). Below is an example of such a "hole" at a particular zoom level in Germany.

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/2140440/101881047-364dae00-3bd7-11eb-97ff-2f2a7e6b688b.png">

**Comment by nvkelso** [comment]
That looks like an oriented buffer around the A3 text label. But the other road labels don't have that issue. I don't remember seeing a bug like this while at Mapzen working on Tangram-based styles, you might have found something novel! :)

**Comment by burritojustice** [comment]
I took a look at the yaml that was generated and noticed this:

```
  highway_name_major:
    data: {layer: transportation_name, source: openmaptiles}
    draw:
      text:
        blend_order: 37
        buffer: 350px
        font: {family: Open Sans Regular, fill: '#ccc', priority: 962, size: 13, transform: uppercase}
        move_into_tile: false
        style: overlay_text
```
In the source .json you have this:

```      "id": "highway_name_major", 
      "layout": {
        "symbol-avoid-edges": true, 
        "symbol-placement": "line", 
        "symbol-spacing": 350,
```
I suspect you're trying to avoid label repetition -- if so, you'll want to use `repeat_distance` instead of a buffer.

https://tangrams.readthedocs.io/en/latest/Syntax-Reference/draw/#repeat_distance

**Comment by bcamper** [comment]
Good eye @burritojustice! Yes, `buffer: 350px` will ensure there is at least 350px of space around each label, hence that one lonely A3 in the middle 🤣 

`repeat_distance` is indeed useful for preventing the same label text from repeating too closely. It doesn't affect _where_ the labels are placed though, just if they are shown or hidden (the default value is usually fine too though).

For label _placement_ along a line, the parameters you want that correspond to MBGL are documented here: https://tangrams.readthedocs.io/en/master/Syntax-Reference/draw/#placement

So I believe the equivalent would be:
```
draw:
  text:
    placement: spaced
    placement_spacing: 350px
    ...
```

There are also some more esoteric options like https://tangrams.readthedocs.io/en/master/Syntax-Reference/draw/#placement_min_length_ratio.

Some examples from Mapzen basemaps (with zoom stops on some of those params):
https://github.com/tangrams/bubble-wrap/blob/ab18c141a1f782f113c449e2df86ed966598eb75/bubble-wrap-style.yaml#L1601-L1602
https://github.com/tangrams/bubble-wrap/blob/ab18c141a1f782f113c449e2df86ed966598eb75/bubble-wrap-style.yaml#L1556-L1567

**Comment by ianthetechie** [comment]
Wow, thanks a lot guys for taking the time to look through these! Yes, you're right. That was totally an implementation error on my end. Using `placement: spaced` and `placement_spacing: 350px` does the trick.

I may circle back next week if I'm unable to roughly match the label precedence, but I did find docs on that so I'll check those first.

Cheers!

**Comment by ianthetechie** [comment]
I think I've fixed most of the issues I had with priority/precedence of text labels (I accidentally attached the `priority` to the `font` block instead of `text`). However, there's something a bit amiss still. The following sequence illustrates how labels that are supposed to be a lower (higher numerically in Tangram) priority can crowd out ones that are supposed to be more important. It looks like the `highway_name_motorway` labels can sometimes crowd out `place_city_large` (screenshots show the difference between 2 scroll wheel clicks of zoom).

<img width="524" alt="image" src="https://user-images.githubusercontent.com/2140440/102305776-2998d380-3fa4-11eb-8e89-a259f267c768.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/2140440/102305818-3c130d00-3fa4-11eb-8a49-78845909c1d5.png">

I've included the two layers below. Maybe someone can spot what I missed.

```yaml
  highway_name_motorway:
    data:
      layer: transportation_name
      source: openmaptiles
    draw:
      text:
        blend_order: 38
        font:
          family: Open Sans Regular, Noto Sans Arabic Regular, Noto Sans Ethiopic
            Regular, Noto Sans Thai Regular, Noto Sans Khmer Regular, Noto Sans Lao
            Regular, Noto Sans Myanmar Regular, Noto Sans Tamil Regular, Noto Sans
            Bengali Regular, Noto Sans Devanagari Regular, Noto Sans Hebrew Regular,
            Noto Sans Armenian Regular, Noto Sans Georgian Regular, Noto Sans JP Regular,
            Noto Sans SC Regular, Noto Sans TC Regular, SeoulNamsan M, Noto Sans Regular
          fill: hsl(214, 11%, 65%)
          size: 14
          stroke:
            color: hsl(0, 0%, 20%)
            width: 2.0px
        move_into_tile: false
        placement: spaced
        placement_spacing: 350px
        priority: 961
        style: overlay_text
        text_source: ref
    filter:
      all:
      - $geometry: line
      - class: motorway
```



```yaml
  place_city_large:
    data:
      layer: place
      source: openmaptiles
    draw:
      icons:
        blend_order: 44
        order: 44
        size: 40.0%
        sprite: circle-alt-11
        text:
          anchor: right
          blend_order: 44
          font:
            family: Open Sans Regular, Noto Sans Arabic Regular, Noto Sans Ethiopic
              Regular, Noto Sans Thai Regular, Noto Sans Khmer Regular, Noto Sans
              Lao Regular, Noto Sans Myanmar Regular, Noto Sans Tamil Regular, Noto
              Sans Bengali Regular, Noto Sans Devanagari Regular, Noto Sans Hebrew
              Regular, Noto Sans Armenian Regular, Noto Sans Georgian Regular, Noto
              Sans JP Regular, Noto Sans SC Regular, Noto Sans TC Regular, SeoulNamsan
              M, Noto Sans Regular
            fill: '#9aa2ac'
            size:
            - - 4
              - '11'
            - - 12
              - '18'
            - - 14
              - '22'
            stroke:
              color: hsl(0, 0%, 20%)
              width: 2.0px
            transform: uppercase
          move_into_tile: false
          priority: 955
          style: overlay_text
          text_source: 'function() { return `${feature["name:latin"] || ''''}

            ${feature["name:nonlatin"] || ''''}`.trim() }'
    filter:
      all:
      - $geometry: point
      - all:
        - not:
            capital: 2
        - rank:
            max: 4
        - class: city
```
